name: bold_icon
description: "Drop-in Flutter Icon widget with fontWeight support — make any icon bold."
version: 1.0.0
homepage: https://www.mokaily.com/
repository: https://github.com/mokaily/bold_icon

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
